# Site
repository:  alexanderdyndin/alexanderdyndin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dyndin Aleksandr / Дындин Александр
title: Android Developer
email: dyndinalexandr13@gmail.com
#website: www.github.com/alexanderdyndin

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  alexanderdyndin

# Additional icon links
additional_links:
- title: telegram
  icon: fab fa-telegram
  url: https://telegram.me/Alexandr_dyndin
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
about_title: About me / Обо мне
#about_profile_image: images/profile.jpg
about_content: |
    EN:

    Hi! I'm Aleksandr Dyndin, an Android Developer with expertise in Kotlin and modern Android development. I've worked in various team environments, from startups to established companies. I also enjoy building robust, scalable applications.
    In the last few years, I have been working in big tech (Avito LLC), focusing on real estate and geo units.
    I have extensive experience launching features and complete products.

    RU:

    Привет! Меня зовут Александр Дындин, Android разработчик c многолетним опытом Android разработки на Kotlin. Работал как в стартапах, так и в крупных компаниях. Люблю создавать качественные, масштабируемые продукты.
    Последние несколько лет работал в крупных компаниях (таких, как Авито) в продуктах связанных с недвижимостью и геолокацией.
    Имею большой опыт как в запуске отдельных фич, так и целых продуктов.
  

content:
  - title: Skills / Скиллы
    layout: list
    content:
      - layout: left
        title: Android
        description: |
          - UI: Compose (Jetpack/Multiplatform), Android View
          - Network: Rest, Websockets
          - DI: Koin, Dagger 2 (pure Dagger 2, Hilt, Anvil)
          - Async: Coroutines, RxJava
          - Other: HLS Video Streaming (Exoplayer), CameraX
      - layout: left
        title: Instruments / Инструменты
        description: |
          Android Studio, Git (Github, Bitbucket, Gitlab), Jira, Confluence, Firebase, Google Play Console, Figma, Miro


  - title: Projects / Проекты
    layout: list
    content:
      - layout: left
        title: Avito
        caption: 100+ million downloads across all Android app stores / 100+ миллионов загрузок во всех магазинах Android приложений
        link_text: https://www.avito.ru/
        additional_links:
          - title:  RuStore
            url: https://www.rustore.ru/catalog/app/com.avito.android
        description: |
              EN:

              Avito is a Russian classified advertisements website with sections devoted to general goods for sale, jobs, real estate, personals, cars for sale, and services. Avito is the most popular classifieds site in Russia and is the biggest classifieds site in the world.
              Avito applications is removed from Google Play Store and App Store and now available on RuStore and other app stores on Android.

              RU:

              Авито — российский интернет-сервис для размещения объявлений о товарах, недвижимости, вакансиях и резюме на рынке труда, а также услугах, занимающий первое место в мире среди сайтов объявлений.

      - layout: left
        title: WASD
        caption: 500+ thousand downloads / 500+ тысяч загрузок
        description: |
              EN:

              Mobile application for the WASD.tv streaming platform for gamers. Rebranded to NUUM with a shift towards short-form clips in 2023 and discounted in 2024.

              RU:

              Мобильное приложение стриминговой платформы Wasd.tv для геймеров. Было переименовано в NUUM со сменой направления на короткие клипы в 2023 году и окончательно закрыто в 2024 году.

      - layout: left
        title: Edugma
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Edugma/app
        description: |
              EN:

              Decentralized mobile application for educational institutions. Any educational institution can connect to it by setting up their own node and implementing the required API. Currently developing the application itself + a node for Moscow Polytechnic University.

              RU:

              Децентрализованное мобильное приложение для учебных заведений. К нему может подключиться любое учебное заведение, подняв свой узел и реализовав нужный API. В процессе разработки само приложение + узел для Московского Политеха.
      
      - layout: left
        title: mospolyhelper
        caption: 3000+ downloads
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/mospolyhelper/mospolyhelper-android
          - title:  Google Play
            icon: fab fa-google-play
            url: play.google.com/store/apps/details?id=com.mospolytech.mospolyhelper
        description: |
              EN:

              Mobile application for Moscow Polytechnic University.
              Android app + Asp Net Core Web Api + website on Vue.js
              Now discountied.

              RU:

              Мобильное приложение для Московского Политеха.
              Android приложение + Asp Net Core Web Api + вебсайт на Vue.js

  - title: Working Experience / Опыт работы
    layout: list
    content:
      - layout: left
        title: Avito
        sub_title: Senior Android Developer
        caption: January 2023 — now
        description: |
          EN:

          Worked 2 years in the real estate unit:
          - researched and launched a secondary real estate sales flow with a realtor on the Avito platform called "Comfortable Deal". The project was successfully launched and showed good results in conversion and deal volume (details cannot be disclosed due to NDA)
          - similarly, launched "Virtual Deal Cabinet" from scratch, creating a platform for integrating various flows such as "Comfortable Deal", "New Construction Purchase", "Mortgage Acquisition", integrating them into our product, while creating a platform for embedding and launching similar real estate-related products
          - maintained and developed the main Avito application, making improvements to the design system, various common and architectural components
          - actively engaged in T-shaping, taking on iOS and Backend development tasks

          Then, moved to the geo unit:
          - launched multiple A/B experiments related to user addresses
          Worked with MediaSession, Exoplayer (HLS Streaming), Coroutines, Dagger 2, Retrofit, Websockets, Firebase Analytics, RxJava, Jetpack Compose.

          RU:

          Работал 2 года в юните недвижимости:
          - проресерчили и запустили флоу продажи вторичной недвижимости с риелтором на платформе Авито "Комфортная сделка" проект был успешно запущен и показал хорошие результаты по конверсии и количеству сделок (подробности не могу раскрыть из-за NDA)
          - аналогично, с нуля запустили "Виртуальный кабинет сделок" в рамках которого сделали платформу для интеграции различных флоу, таких как "Комфортная сделка", "Покупка новостройки", "Получение ипотеки", интегрировав их в наш продукт, попутно создав платформу для встраивания и запуска аналогичных продуктов, связанных с недвижимостью.
          - поддерживал и развивал основное приложение Авито, внося улучшения в дизайн систему, различные общие и архитектурные компоненты
          - активно занимался T-shaping'ом, забирая задачи на разработку iOS и Backend

          Далее, перешел в юнит гео:
          - запустили множество аб экспериментов связанных с пользовательскими адресами
          Работал с MediaSession, Exoplayer (HLS Streaming), Coroutines, Dagger 2, Retrofit, Websockets, Firebase Analytics, RxJava, Jetpack Compose.

      - layout: left
        title: MTS (WASD.tv)
        sub_title: Android Developer
        caption: September 2021 — December 2022
        description: |
          EN:

          - Implemented background media playback
          - Developed product features
            - clips
            - favorites
            - authentication
            - feed
            - post creation
            - in-app advertising
          - Provided support
            - bug fixes
            - refactored legacy code (migration to Single Activity, MVP to MVI, etc)
            - maintained codebase
          Worked with Foreground Service, MediaSession, Exoplayer (HLS Streaming), Coroutines, Dagger 2, Retrofit, Websockets, Firebase Analytics, RxJava, Jetpack Compose.

          RU:

          Приложение для просмотра стримов, 500+ тысяч загрузок.
          - сделал воспроизведение медиа в фоне
          - реализовывал продуктовые фичи
            - клипы
            - избранное
            - авторизация
            - лента постов
            - создание постов
            - работал с рекламой в приложении
          - осуществлял поддержку
            - фиксил баги
            - рефаторил легаси код (переход на Single Activity, с MVP на MVI)
            - поддерживал кодовую базу в актуальном состоянии
            - занимался оптимизацией скорости сборки проекта
          Работал с Foreground Service, MediaSession, Exoplayer (HLS Streaming), Coroutines, Dagger 2, Retrofit, Websockets, Firebase Analytics, RxJava, Coroutines, Jetpack Compose.

      - layout: left
        title: Intergroup
        link: https://github.com/alexanderdyndin/ig-app
        sub_title: Android Developer
        caption: September 2020 — August 2021
        description: |
          EN: 

          Startup, an attempt to create a social network
            - implemented image and video upload and viewing in posts
            - implemented likes and comments
            - implemented post feed
            - implemented authentication and registration
            - worked with in-app advertising
            - refactored legacy code (migration to Single Activity, from MVP to MVVM, from Android Support Library to AndroidX)

          RU: 

          Стартап, попытка создать социальную сеть
            - сделал загрузку и просмотр картинок и видео в постах
            - реализовал лайки и комментарии
            - реализовал ленту постов
            - реализовал авторизацию и регистрацию
            - работал с рекламой в приложении
            - рефаторил легаси код (переход на Single Activity, миграция с MVP на MVVM, миграция с Android Support Library на AndroidX)

  - title: Education / Образование
    layout: list
    content:
      - layout: left
        title: Moscow Polytechnic University
        caption: 2022 - present
        sub_title: Master's Degree "Information Systems and Technologies. Mobile Technologies"
        description: |
          Currently studying while working in parallel.
          
      - layout: left
        title: Moscow Polytechnic University
        caption: 2018 - 2022
        sub_title: Bachelor's Degree "Information Systems and Technologies"
        description: |
          During my studies, I tried many different directions and programming languages before finding my passion in mobile development. I worked in various teams (ranging from 2 to 5 people).

      - layout: left
        title: Serpukhov Technical College
        caption: 2014 - 2018
        sub_title: Computer Systems Programming
        description: |
          During my studies, I primarily worked with C#.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
